language: ruby
cache: bundler
rvm:
- 2.2.0
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_53dcbc395559_key -iv $encrypted_53dcbc395559_iv
  -in id_rsa_deploy.enc -out id_rsa_deploy -d
- chmod 600 id_rsa_travis
- eval "$(ssh-agent -s)"
- ssh-add id_rsa_travis
before_script:
- echo -e "Host org-osdevelopers.rhcloud.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- mkdir build
- cd build
- git init
- git remote add production $REMOTE
- git pull production master
- git config --global user.email $USERMAIL
- git config --global user.name $USERNAME
- cd ..
- bundle exec middleman build
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then bundle exec middleman deploy; fi
env:
  global:
  - secure: Vz76CGym9gzG3Yg1i+JghWVD4b5UrCVSYbUF1Gr5J2BFj9YJN0HEI1gcHNonCdpbESR7LuwGJtPrcEkutqVKr056UzkeZd+HQOsDwNzppqrl1D4F/Vd+OZXXygkVEHamZW0ouWpE1+AEYsG5L5OC4BqNpB7H+Zbq8sco8IoD+u+NHyzzacrczWidFJmdn6bonXIknnpIzac9WFT+zJv8hMlRqFZD3fH62N6pcFNVZL9nOeH88ScfSEZBJis90KGsLolmvT6eSm649erl768l0FuidjKFg9bF02WZDIqmAP9cNFYvy0oIKuW8aPxTfSpUrHQ+d5SzPZSU1UrFXkENbWHGheeJmrADiCQG4mtfpKMRmuf2Ql3a4HW87Fh+3RDc8iyZUGkgxumkdgRy0xJoKOEKymXKx+P8fK/KBbsTJbYvZWhvhY74lnE6MQrUGcnWG5A71+jD05wDrITPYyocAT58+9pR7wR1jdi7gw7387yIZj5pSiwVyS2Cu5GFhXSDf515a8G6+dw8BQzyOHoKW+jd27vG2KpukhQ8vrklZ9Tqcf33ah/5pAfs/2at/eYMf0i2dv7EGBj4ZUJMxiRkDk+YjainEsk6WkUCDOUdAqj4BLvBDIY5HQOrDGixzbSnnFIo0DufVIPv0VbHeKaepIqLBD+X2NgCrNLYRxQqKOk=
  - secure: coBPTZUlPCZP+ai6o+/V8LI2cfHDWYnqBuJmM910e50mxrK1fY3LzQ9BBvbarV4ryaMDcCLxBI+E5NdchGUQsuLoiHlxkHtzK2m1WgHYXGe9DqcOFgrDCVTzHw32JcD/psFA+eXxkRnjuGMe6Dod2SYDZUXB17l0Z6XupIxhlXPWGFsJXSWiJ3BOyKdbpBFX7YEffzn76U1eUKJG1lClnkAeRDN8MCV1krifnO+Ai0XVm3Ig3H0P/kh8N4T8gHJExqM7rZUWiILZiidISuzFfMsfjv+xfSo43eIAEIDSpMGbgK3GB782Y1YfYf7LbL+LqC7qo4fF23noT7UMUHrKW5ilWNmzJnC62smrY5d5wQwMVRnXqjGoL9/yVXSLIcYcUItt7A0o+7WnahH+T7Kqr9LUtxghvHDDQWomEDCw33Badkri0IMfpKb/SLEWbRSg9ncbT/GSxINn9EMqIdp5pvihNTIkuIegSd+KNbLJ+egsohfNansTpIRCTuB2ZJ8OXETgs2STCnGKneeNcIObRS6R5pkfi8sOEbnIXwLlE6rJxTslAtgmt0NphUStjKQIKqrBICxJ4R5Xa/3Au0qQAj4T2YxXtU8raXOalzjy/E/HRXHS/73vkjPYkz9In7yb9QKU4N+b1aUHA+3gyZdx/txdLvoyVCiRr4pticRcMXw=
  - secure: lvQ9fJmkrfRZfWg3B3/WbjE16umETbzohPf2AriySBXh6eL5feGAtolW1F7lOTedJnmkTG1ckcpxyXHxgrxnFm0ifi9yP9CMJLdiwBfrz9gkWvAhNsSWEzRj0qQclQYODSMm5H0oLVxNbmgIfA6yArY2sNuUcZ7Q+R+k84ed6+Df+vMA5VQTXPg9gvxi/FuEwM/VsMQUP8wTQXU40wjRifyqfW3vDX0YtSWxIRAwOXxmocMb1q2l0K9TyZ0mt94oXMRhAg2dbfS9hEmv1y1h8ugYTzT2lt00Hj3TqlBI7FBRzybUlZtQMvgkcIo4N0jL9fyCjy+xtK8ORUo9Hvu74YgKBgSiguUAm599lBAIH2dfhzDUXZ5mAWvKy9/Q8ULmIWgDFNKORzN/B0+bwPDc9G/eHj+fsPlpg1HkWsyxbEIbPd5C7uQPHCkpbbV3SlJjm3MgEhfAbAnCDftezNRYTMWYvGd1arUD/spNHC0mc0CvQy/+ayc7HAbOu/E/4ImIGZd1PckKSWHwN7nxQ/W9NnOkLoYYvFj432gJm0SiNXDsqMGkm8Y1PSwSMkHolKm7FQXf1FhOYC1Ps9idTLPV0XGG25FxH7WgoIrb3Y9sH/1tSNP4JYVdjuOl6pbSwMgNXPm9BJhmC0UndlURUnaDeoqARvWqfOYCev2K8Yfcgb0=
