language: ruby
cache: bundler
rvm:
- 2.2.0
branches:
  only:
  - master
script:
- mkdir build
- |
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
  # if going to deploy, set up the git
    echo -e "Host org-osdevelopers.rhcloud.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    openssl aes-256-cbc -K $encrypted_53dcbc395559_key -iv $encrypted_53dcbc395559_iv -in id_rsa_deploy.enc -out id_rsa_deploy -d
    chmod 600 id_rsa_deploy
    eval "$(ssh-agent -s)"
    ssh-add id_rsa_deploy
    cd build
    git init
    git config --global user.email $USERMAIL
    git config --global user.name $USERNAME
    git remote add production $REMOTE
    git pull production master
    cd ..
  fi
  # if not deploying, PRs are just built
- bundle exec middleman build
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then bundle exec middleman deploy; fi
env:
  global:
  - secure: FyFEObLs3M5A34W7MYDGI97oNbXh7QFmLdDI8e9jPphelyY//jQcIiskUjtS4+XbDzXBnJhsh0v0Txin8vCAMNXGx7bWVRk1TJ9gSvoSKHwXUlIijiYztMntPwj+zbDlGop8Ynv/V9JdJiC+8mAcANmhf/V3FmdXkGqcLGLHqRY=
  - secure: N4H+qVqf8G/fhX2pK9abUzjtvnQOVN3zR5aizro2FQIKNhcfbtbFVMxZcVWoOpqgp/91/iK8u8nfq4PovRg/j5FYCs8Yq97FJUxsrg+CpxI2zxVMwmKPGXU3FuzWLswaCESFOcq34MFUjZfJWaO+65P2Yo+jlWgZiNAIVq0BN+I=
  - secure: b0Ppim1qoKWY+T/ueemZ35GeAMvA4UkgigPtK1+fb6nerkLpXBmU3vn0tQYcjtqQtEWPWYhOS68mF2m00ozBugKUa9q4uWXONCzqU7IQOBG5SaUJYHaNkWiyseNBoIUxmEsFuTQGFo/he4o0GJMdb9X6WFu3aATjhsp3kh1s5H8=
